export default {
	FILTER_CONTAINER: 'FILTER_CONTAINER',
	FILTER_CONTAINER_TOGGLE: 'FILTER_CONTAINER_TOGGLE',
	MULTIPLE_CHOICE_FILTER: {
		BUTTON: 'MULTIPLE_CHOICE_FILTER_BUTTON',
		OPTION: 'MULTIPLE_CHOICE_FILTER_OPTION',
		COMPOSED_OBJECTS_RESULTS_LIST: 'MULTIPLE_CHOICE_FILTER_COMPOSED_OBJECTS_RESULTS_LIST'
	},
	TABLE_ROW: 'TABLE_ROW',
	MULTI_PASTE_INSERT_BUTTON: 'MULTI_PASTE_INSERT_BUTTON',
	MULTI_PASTE_SAVE_BUTTON: 'MULTI_PASTE_SAVE_BUTTON',
	LEHRENDE_NAME_ANZEIGE: 'LEHRENDE_NAME_ANZEIGE',
	INPUT_AUTO_COMPLETE: 'INPUT_AUTO_COMPLETE',
	INPUT_EINRICHTUNG_SELECT: 'INPUT_EINRICHTUNG_SELECT',
	DROPDOWN_AUTO_COMPLETE: 'DROPDOWN_AUTO_COMPLETE',
	INPUT_LEHRENDEN_SELECTION: 'INPUT_LEHRENDEN_SELECTION',
	INPUT_EINRICHTUNG_SELECTION: 'INPUT_EINRICHTUNG_SELECTION',
	BUTTON_SAVE_TERMINBEARBEITUNG: 'BUTTON_SAVE_TERMINBEARBEITUNG',
	BUTTON_SAVE_AND_NEXT_TERMINBEARBEITUNG: 'BUTTON_SAVE_AND_NEXT_TERMINBEARBEITUNG',
	LEHRENDE_EINRICHTUNG_ANZEIGE: 'LEHRENDE_EINRICHTUNG_ANZEIGE',
	LEHRTAETIGKEIT: 'LEHRTEATIGKEIT',
	ADD_LEHRTAETIGKEIT: 'add-lehrtaetigkeit',
	DELETE_LEHRTAETIGKEIT: 'delete-lehrtaetigkeit',
	CHIP: 'CHIP',
	INPUT_CLEAR: 'INPUT_CLEAR',
	ROW_EDIT: 'ROW_EDIT',
	DRAWER: 'DRAWER',
	DRAWER_CLOSE: 'DRAWER_CLOSE',
	CHOSEN_SELECTION: 'CHOSEN_SELECTION',
	INPUT_START_DATE: 'INPUT_START_DATE',
	INPUT_END_DATE: 'INPUT_END_DATE',
	SELECT: 'SELECT',
	SELECT_ITEM: 'SELECT_ITEM',
	DROPDOWN_BUTTON: 'DROPDOWN_BUTTON',

	SHOWCASE: {
		EDITABLE_TABLE: 'EDITABLE_TABLE'
	}
}
